### ISSUE TITLE
Error while running `docker-compose up enterprisesearch`

### ISSUE THREAD

**Issue by Pierrci** [elishowk/node-search-demo#1]
I tried to follow the readme to run the demo, but I get an error at the first step, here is the stack trace:

```
Starting elishowk_elasticsearch_1 ... done
Starting elishowk_enterprisesearch_1 ... done
Attaching to elishowk_enterprisesearch_1
enterprisesearch_1  | Custom Enterprise Search configuration file detected, not overwriting it (any settings passed via environment will be ignored)
enterprisesearch_1  | Found java executable in PATH
enterprisesearch_1  | Java version detected: 1.8.0_252 (major version: 8)
enterprisesearch_1  | Enterprise Search is starting...
enterprisesearch_1  | *** [DEPRECATION WARNING] The setting '#/ent_search/auth/source' is deprecated and will be removed in version '8.0.0'. Please use the new auth config format ent_search.auth.<auth_name>.source.
enterprisesearch_1  | Unexpected exception while running Enterprise Search:
enterprisesearch_1  | Error: elasticsearch: Name or service not known at /usr/share/enterprise-search/lib/war/gems/gems/manticore-0.7.0-java/lib/faraday/adapter/manticore.rb:88:in `block in call'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/gems/gems/manticore-0.7.0-java/lib/manticore/response.rb:79:in `call'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/gems/gems/manticore-0.7.0-java/lib/faraday/adapter/manticore.rb:92:in `call'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/lib/middleware/request_logging_middleware.class:25:in `call'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/gems/gems/faraday-0.17.3/lib/faraday/rack_builder.rb:143:in `build_response'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/gems/gems/faraday-0.17.3/lib/faraday/connection.rb:387:in `run_request'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/gems/gems/faraday-0.17.3/lib/faraday/connection.rb:138:in `get'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/shared_togo/lib/shared_togo/elasticsearch_checks.class:161:in `check_es_connection_with_retries!'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/shared_togo/lib/shared_togo/elasticsearch_checks.class:33:in `check_es_connection!'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/shared_togo/lib/shared_togo/elasticsearch_checks.class:18:in `block in run!'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/gems/gems/activesupport-4.2.11.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/gems/gems/activesupport-4.2.11.3/lib/active_support/tagged_logging.rb:26:in `tagged'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/gems/gems/activesupport-4.2.11.3/lib/active_support/tagged_logging.rb:68:in `tagged'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/shared_togo/lib/shared_togo/elasticsearch_checks.class:17:in `run!'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/shared_togo/lib/shared_togo/elasticsearch_checks.class:13:in `run!'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/shared_togo/lib/shared_togo.class:256:in `configure_elasticsearch!'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/shared_togo/lib/shared_togo.class:236:in `configure!'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/config/application.class:18:in `<main>'
enterprisesearch_1  |   org/jruby/RubyKernel.java:1016:in `load'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/gems/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:268:in `block in load'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/gems/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:240:in `load_dependency'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/gems/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:268:in `load'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/config/application.rb:1:in `<main>'
enterprisesearch_1  |   org/jruby/RubyKernel.java:974:in `require'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/gems/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `block in require'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/gems/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:240:in `load_dependency'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/gems/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `require'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/shared_togo/lib/shared_togo/cli/command.class:36:in `initialize'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/shared_togo/lib/shared_togo/cli/command.class:10:in `run_and_exit'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/shared_togo/lib/shared_togo/cli.class:143:in `run_supported_command'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/shared_togo/lib/shared_togo/cli.class:125:in `run_command'
enterprisesearch_1  |   /usr/share/enterprise-search/lib/war/shared_togo/lib/shared_togo/cli.class:112:in `run!'
enterprisesearch_1  |   bin/enterprise-search-internal:15:in `<main>'
elishowk_enterprisesearch_1 exited with code 1
```

I tried to google it, but couldn't find anything... Any idea? 🤔

(My env is MacOS 11.2.3 with the latest Docker version)

**Comment by elishowk** [comment]
Hi,

Thanks for your feedback. although I'm not able to reproduce it, I guess container naming is the issue here. 
I also added in the README.md athe step to ensure the docker network bridge is created, but may be you did it already.
Could you try the proposed fix please ?

Thanks a lot !

**Comment by Pierrci** [comment]
I tried adding the 2 `container_name` fields but it didn't change anything, I'm still getting the same error when running `docker-compose up enterprisesearch`, unfortunately :/

(I already had created the `default-bridge-network`)

**Comment by elishowk** [comment]
My second guess is that the elasticsearch container did not boot.
Could you please try this and send me the logs please ?
```
docker-compose down
docker-compose up elasticsearch
```
